### ISSUE TITLE
可以创建一个检测整个站点中外链可用性和安全性

### ISSUE THREAD

**Issue by sxyc1** [fooying/CUS#1]
比如现在的学校或者政府网站中好多年前的发的网址或者链接，这些链接域名已经到期或者被用作黑产。能批量检测的。

**Comment by fooying** [comment]
不好意思，这个项目很多年前的了，现在已经不维护了
要实现这个逻辑其实挺简单的，您可以自己试试
网页爬虫爬取所有外链，然后调用这类安全网址的服务查询网址安全性
